version: '3.7'

services:
  proxy:
    container_name: proxy
    image: traefik:alpine
    restart: always
    labels:
      - "traefik.frontend.rule=Host:monitor.traefik"
      - "traefik.port=8080"
      - "traefik.enabled=true"
      - "traefik.backend.healthcheck.enable=false"
      - "traefik.docker.network=proxy"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: true
    name: proxy
