defaultEntryPoints = ["http"]
logLevel = "DEBUG"

[web]
  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]
  dashboard = true
  debug = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "docker"
  watch = true
  network = "proxy"
  exposedByDefault = false
